### ISSUE TITLE
for...of

### ISSUE THREAD

**Issue by scheul93** [DEGJS/moduleLoader#4]
Brought up as a room for improvement in dialogLoader...

Consider replacing the `for...of` statement with a `forEach` especially since it is [not supported in IE 11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Browser_compatibility) and each project that uses this would need to polyfill for it.

**Comment by aladage** [comment]
Fixed in https://github.com/DEGJS/moduleLoader/pull/5
